apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datetime
  template:
    metadata:
      labels:
        app: datetime
    spec:
      containers:
      - name: datetime
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
