stages:
  - docker
  - deploy

variables:
  version: "2.0"
  image: "megionrx/datetime:${version}"

docker-job:
  stage: docker
  script:
    - docker build --build-arg version="${version}" -t datetime .
    - docker push "${image}"

deploy-job:
  stage: deploy
  script:
    - helm upgrade --install datetime --set image="${image}" .